# alertmanager-configmap

apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: ethereum
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'default'

    receivers:
      - name: 'default'
