apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt-secret
  namespace: ethereum
data:
  # Generate JWT secret: openssl rand -hex 32
  secret: "aced7325ad6f01b0f5a405ac1b04f9fbd768e9d382e953c5bb25487dd874f443"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-data-pvc
  namespace: ethereum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lighthouse-data-pvc
  namespace: ethereum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth
  namespace: ethereum
  labels:
    app: geth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
      - name: geth
        image: ethereum/client-go:latest
        ports:
        - containerPort: 8545
          name: http-rpc
        - containerPort: 8546
          name: ws-rpc
        - containerPort: 30303
          name: p2p
        - containerPort: 8551
          name: auth-rpc
        - containerPort: 6060
          name: metrics
        volumeMounts:
        - name: geth-data
          mountPath: /root/.ethereum
        - name: jwt-secret
          mountPath: /root/jwt
          readOnly: true
        command:
        - geth
        args:
        - --sepolia
        - --syncmode=snap
        - --http
        - --http.addr=0.0.0.0
        - --http.port=8545
        - --http.corsdomain=*
        - --http.vhosts=*
        - --http.api=eth,net,web3
        - --ws
        - --ws.addr=0.0.0.0
        - --ws.port=8546
        - --ws.api=eth,net,web3
        - --cache=1024
        - --maxpeers=50
        - --metrics
        - --metrics.addr=0.0.0.0
        - --metrics.port=6060
        - --authrpc.addr=0.0.0.0
        - --authrpc.port=8551
        - --authrpc.vhosts=*
        - --authrpc.jwtsecret=/root/jwt/secret
        livenessProbe:
          httpGet:
            path: /
            port: 8545
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8545
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "2000m"
      volumes:
      - name: geth-data
        persistentVolumeClaim:
          claimName: geth-data-pvc
      - name: jwt-secret
        configMap:
          name: jwt-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse
  namespace: ethereum
  labels:
    app: lighthouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse
  template:
    metadata:
      labels:
        app: lighthouse
    spec:
      containers:
      - name: lighthouse
        image: sigp/lighthouse:latest
        ports:
        - containerPort: 9000
          name: p2p
        - containerPort: 5052
          name: http-api
        volumeMounts:
        - name: lighthouse-data
          mountPath: /root/.lighthouse
        - name: jwt-secret
          mountPath: /root/jwt
          readOnly: true
        command:
        - lighthouse
        args:
        - bn
        - --network=sepolia
        - --execution-endpoint=http://geth:8551
        - --execution-jwt=/root/jwt/secret
        - --checkpoint-sync-url=https://sepolia.beaconstate.info
        - --http
        - --metrics
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
      volumes:
      - name: lighthouse-data
        persistentVolumeClaim:
          claimName: lighthouse-data-pvc
      - name: jwt-secret
        configMap:
          name: jwt-secret